config/routes.rb
Rails.application.routes.draw do

root to: "static_pages#index"

  resources :skate_maps,        only: [:index, :show]
  resources :skate_spots,       only: [:index, :show]
  resources :user_skate_spots,  only: [:new, :index, :show, :create, :approve, :deny]

  get "/home",                   to: "static_pages#index"
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure",            to: redirect('/')
  get "/signout",                to: "sessions#destroy"


  namespace :administrator do
    resources :admins
    resources :users
    resources :skate_spots
    resources :user_skate_spots do
      member do
        post 'approval'
        post 'denial'
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :skate_spots,      only: [:index, :show]
      resources :user_skate_spots, only: [:index, :show]
    end
  end

end

app/models/skate_spot.rb
class SkateSpot < ActiveRecord::Base
end

app/controllers/administrator/admins_controller.rb
class Administrator::AdminsController < AdminsController
  def index
    
  end
end

app/controllers/administrator/skate_spots_controller.rb
class Administrator::SkateSpotsController < AdminsController
include SkateSpotsHelper
  
  def index
    @spots = SkateSpot.all
  end

  def show
    @spot = SkateSpot.find(params[:id])
    spot_to_hash(@spot)
  end

  def new
    @spot = SkateSpot.new
  end

  def create
    @spot = SkateSpot.create(spot_params)
    redirect_to administrator_skate_spots_path
  end

  def edit
    @spot = SkateSpot.find(params[:id])
  end

  def update
    @spot.update(spot_params)
    redirect_to administrator_skate_spot_path(@spot)
  end

  def destroy
    @spot = SkateSpot.find(params[:id])
    @spot.destroy
    redirect_to administrator_skate_spots_path
  end

  private

  def spot_params
    params.require(:skate_spot).permit(:name,
                                       :address,
                                       :city,
                                       :state,
                                       :zipcode,
                                       :latitude,
                                       :longitude,
                                       :image)
  end
end

app/controllers/administrator/user_skate_spots_controller.rb
class Administrator::UserSkateSpotsController < AdminsController

  def index
    @approved_spots = UserSkateSpot.approved
    @pending_spots  = UserSkateSpot.pending
  end

  def show
    @user_spot = UserSkateSpot.find(params[:id])
  end

  def destroy
    @spot = UserSkateSpot.find(params[:id])
    @spot.destroy
    redirect_to administrator_user_skate_spots_path
  end

  def approval
    UserSkateSpot.find(params[:id]).update_attribute(:approval, true)
    redirect_to :back
  end

  def denial
    UserSkateSpot.find(params[:id]).update_attribute(:approval, false)
    redirect_to :back
  end

  private

  def user_spot_params
    params.require(:user_skate_spot).permit(:approval)
  end
end

app/controllers/skate_spots_controller.rb
class SkateSpotsController < ApplicationController
  include SkateSpotsHelper

  def index
    @spots = SkateSpot.all
    spots_to_hash(@spots)
  end

  def show
    @spot = SkateSpot.find(params[:id])
    spot_to_hash(@spot)
  end
end

app/helpers/skate_spots_helper.rb
module SkateSpotsHelper

  def spots_to_hash(spots)
    @hash   = Gmaps4rails.build_markers(spots) do |spot, marker|
      @spot = spot
      marker.infowindow render_to_string(:partial => "info")

      marker.lat spot.latitude
      marker.lng spot.longitude
    end
  end

  def spot_to_hash(spot)
    @hash  = Gmaps4rails.build_markers(spot) do |spot, marker|
      marker.lat spot.latitude
      marker.lng spot.longitude
    end
  end
end

app/views/administrator/skate_spots/_form.html.erb
<div class="form-zipper">
  <%= form_for [:administrator, @spot], html: {multipart: true, class: "form-horizontal", role: "form", } do |f| %>
    <div class="form-group">
      <div class="col-md-6 col-md-offset-3">
        <%= f.label :name_your_spot, :class => 'control-label'%>
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-6 col-md-offset-3">
        <%= f.label 'Address / nearest cross streets', :class => 'control-label'%>      
        <%= f.text_field :address, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-5 col-md-offset-3">
        <%= f.label :city, :class => 'control-label'%>
        <%= f.text_field :city, :class => 'form-control' %>
      </div>
      <div class="col-md-1">
        <%= f.label :state, :class => 'control-label'%>
        <%= f.select(:state, options_for_select(us_states, "CO")) %>
      </div>
    </div>

    <div class="form-group" >
      <div class="col-md-3 col-md-offset-3">
        <%= f.label :zipcode, :class => 'control-label'%>
        <%= f.text_field :zipcode, :class => 'form-control' %>
      </div>
      <div>
        <p class="col-md-3"><%= f.label :image, class: "control-label"%></p>
        <div class="col-md-4"><%= f.file_field :image %></div>
      </div>
    </div>

    <div class="form-group" >
      <div class="col-md-3 col-md-offset-3">
        <%= f.label :latitude, :class => 'control-label'%>
        <%= f.text_field :latitude, :class => 'form-control'%>
      </div>

      <div class="col-md-3">
        <%= f.label :longitude, :class => 'control-label'%>
        <%= f.text_field :longitude, :class => 'form-control'%>
      </div>
    </div>
    <div class="form-group" style="padding-bottom:15px;">
      <div class="col-md-4 col-md-offset-4">
          <%= f.submit "Submit", :class => "btn btn-success btn-lg" %>
      </div>
    </div>
  <% end %>
</div>

app/views/administrator/skate_spots/edit.html.erb
<div class="form-container" style="padding-top:30px;">
  
  <div style="padding-top:1px;">
    
    <div class="form-header">
      <h3>You can edit the information for <%= "#{@spot.name}" %> below.
    </div>
    <%= render partial: "form" %>
  </div>
</div>

app/views/administrator/skate_spots/index.html.erb
<div class="admin-skate-table">
  <%= link_to "Add New Skate Park", new_administrator_skate_spot_path, class: "btn btn-primary btn-lrg" %>
  <%= link_to "Manage User Skate Spots", administrator_user_skate_spots_path, class: "btn btn-primary btn-lrg", style: "margin-left:10px;"%>
  <%= link_to "Dashboard Home", administrator_admins_path, class: "btn btn-primary btn-lrg", style: "margin-left:10px;" %>
  <table class="table">
    <thead class="admin-thead">
      <td>Skate Park</td>
      <td>City</td>
      <td>State</td>
      <td>Update</td>
      <td>Delete</td>
    </thead>
    <tbody>
      <% @spots.each do |spot| %>
      <tr>
        <td><%= link_to spot.name, administrator_skate_spot_path(spot) %></td>
        <td><%= spot.city %></td>
        <td><%= spot.state %></td>
        <td><%= link_to "Edit", edit_administrator_skate_spot_path(spot), class: "btn btn-warning btn-lrg" %></td>
        <td><%= link_to "Delete", administrator_skate_spot_path(spot), method: :delete, class: "btn btn-danger btn-lrg" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/administrator/skate_spots/new.html.erb
<div class="form-container" style="padding-top:30px;">
  
  <div style="padding-top:1px;">
    
    <div class="form-header">
      <h3>Add a new Skate Park </h3>
    </div>
    <%= render partial: "form" %>
  </div>
</div>

app/views/administrator/skate_spots/show.html.erb
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=762717537134813&version=v2.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

<br/>
<br/>
<br/>
<div class="container">
  <div>
    <%= link_to "Manage Skate Parks", administrator_skate_spots_path, class: "btn btn-primary btn-lrg", style: "margin-right:10px;" %>
  <%= link_to "Manage User Skate Spots", administrator_user_skate_spots_path, class: "btn btn-primary btn-lrg" %>
  <%= link_to "Manage Current Users", administrator_users_path, class: "btn btn-primary btn-lrg", style: "margin-left:10px;" %>
  <div class="spot-show" style="float:left">
    <h1><%= @spot.name %></h1>
    <p><%= image_tag(@spot.image, height: '300', width: '500', style: 'border-style:solid; border-width:3px; border-radius: 15px;') %></p>
    <p><%= link_to "Edit This Skatepark", edit_administrator_skate_spot_path(@spot), class: "btn btn-primary btn-lrg" %></p>
  </div>
  
      <div class="row skate-show">

        <div class="col-lg-6">
          <h4><%= @spot.address %></h4>
          <p><%= @spot.city%>, <%= @spot.state%> <%= @spot.zipcode%></p>
          <% if current_user %>
            <div class="fb-share-button" data-href="<%= request.original_url %>" data-layout="button_count" data-width="200"></div>
          <% end %>
        </div>

        <div class="col-lg-6">
          <div id="map-show"></div>

        </div>
      
      </div>

    </div> <!-- /container -->


  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {
      zoom: 5
    }, 
    internal: {id: 'map-show'}}, 
    function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);

      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
  </script>