config/routes.rb
Rails.application.routes.draw do

root to: "static_pages#index"

  resources :skate_maps,        only: [:index, :show]
  resources :skate_spots,       only: [:index, :show]
  resources :user_skate_spots,  only: [:new, :index, :show, :create, :approve, :deny]

  get "/home",                   to: "static_pages#index"
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure",            to: redirect('/')
  get "/signout",                to: "sessions#destroy"


  namespace :administrator do
    resources :admins
    resources :users
    resources :skate_spots
    resources :user_skate_spots do
      member do
        post 'approval'
        post 'denial'
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :skate_spots,      only: [:index, :show]
      resources :user_skate_spots, only: [:index, :show]
    end
  end

end

app/models/user_skate_spot.rb
class UserSkateSpot < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :user

  scope :approved, -> { where(approval: true) }
  scope :pending,  -> { where(approval: false) }

  def approve(spot)
    spot.approval = true
    spot.save!
  end

  def deny(spot)
    spot.approval = false
    spot.save!
  end
end

app/controllers/administrator/admins_controller.rb
class Administrator::AdminsController < AdminsController
  def index
    
  end
end

app/controllers/administrator/skate_spots_controller.rb
class Administrator::SkateSpotsController < AdminsController
include SkateSpotsHelper
  
  def index
    @spots = SkateSpot.all
  end

  def show
    @spot = SkateSpot.find(params[:id])
    spot_to_hash(@spot)
  end

  def new
    @spot = SkateSpot.new
  end

  def create
    @spot = SkateSpot.create(spot_params)
    redirect_to administrator_skate_spots_path
  end

  def edit
    @spot = SkateSpot.find(params[:id])
  end

  def update
    @spot.update(spot_params)
    redirect_to administrator_skate_spot_path(@spot)
  end

  def destroy
    @spot = SkateSpot.find(params[:id])
    @spot.destroy
    redirect_to administrator_skate_spots_path
  end

  private

  def spot_params
    params.require(:skate_spot).permit(:name,
                                       :address,
                                       :city,
                                       :state,
                                       :zipcode,
                                       :latitude,
                                       :longitude,
                                       :image)
  end
end

app/controllers/administrator/user_skate_spots_controller.rb
class Administrator::UserSkateSpotsController < AdminsController

  def index
    @approved_spots = UserSkateSpot.approved
    @pending_spots  = UserSkateSpot.pending
  end

  def show
    @user_spot = UserSkateSpot.find(params[:id])
  end

  def destroy
    @spot = UserSkateSpot.find(params[:id])
    @spot.destroy
    redirect_to administrator_user_skate_spots_path
  end

  def approval
    UserSkateSpot.find(params[:id]).update_attribute(:approval, true)
    redirect_to :back
  end

  def denial
    UserSkateSpot.find(params[:id]).update_attribute(:approval, false)
    redirect_to :back
  end

  private

  def user_spot_params
    params.require(:user_skate_spot).permit(:approval)
  end
end

app/controllers/user_skate_spots_controller.rb
class UserSkateSpotsController < ApplicationController
  include UserSkateSpotsHelper

  def index
    @user_spots = UserSkateSpot.approved
    user_spots_to_hash(@user_spots)
  end

  def show
    @user_spot = UserSkateSpot.find(params[:id])
    user_spot_to_hash(@user_spot)
  end

  def new
    @spot = UserSkateSpot.new
  end

  def create
    @spot = UserSkateSpot.create(spot_params)
    flash[:notice] = "Your spot has been submitted, check your email for details on approval"
    redirect_to user_skate_spots_path
  end

  private

  def spot_params
    params.require(:user_skate_spot).permit(:name,
                                            :address,
                                            :city,
                                            :state,
                                            :zipcode,
                                            :latitude,
                                            :longitude,
                                            :image,
                                            :approval)
  end
end

app/helpers/user_skate_spots_helper.rb
module UserSkateSpotsHelper

  def user_spots_to_hash(user_spots)
    @hash   = Gmaps4rails.build_markers(user_spots) do |spot, marker|
      @spot = spot
      marker.infowindow render_to_string(:partial => "info")

      marker.lat spot.latitude
      marker.lng spot.longitude
    end
  end

  def user_spot_to_hash(user_spot)
    @hash  = Gmaps4rails.build_markers(user_spot) do |spot, marker|
      marker.lat spot.latitude
      marker.lng spot.longitude
    end
  end
end

app/views/administrator/user_skate_spots/edit.html.erb
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=762717537134813&version=v2.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

<br/>
<br/>
<br/>
<div class="container">
  <div class="spot-show" style="float:left">
    <h1><%= @spot.name %></h1>
    <p><%= image_tag(@spot.image, height: '300', width: '500', style: 'border-style:solid; border-width:3px; border-radius: 15px;') %></p>
  </div>
  <div class="row skate-show">
    <div class="col-lg-6">
      <h4><%= @spot.address %></h4>
      <p><%= @spot.city%>, <%= @spot.state%> <%= @spot.zipcode%></p>
    </div>
    <div class="col-lg-6">
      <div id="map-show"></div>
    </div>
  </div>
</div> <!-- /container -->
<div>
  
  <% if @spot.approval == true %>
    <%= link_to "Deny this spot", @spot.deny(@spot), method: :post %>
  <% else %>
    <%= link_to "Approve this spot", @spot.approve(@spot), method: :post %>
    <% end %>
</div>

  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {
      zoom: 5
    }, 
    internal: {id: 'map-show'}}, 
    function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);

      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
  </script>

app/views/administrator/user_skate_spots/index.html.erb
<div>
    <%= link_to "Add New Skate Park", new_administrator_skate_spot_path, class: "btn btn-primary btn-lrg" %>
  <%= link_to "Manage User Skate Spots", administrator_user_skate_spots_path, class: "btn btn-primary btn-lrg", style: "margin-left:10px;"%>
  <%= link_to "Dashboard Home", administrator_admins_path, class: "btn btn-primary btn-lrg", style: "margin-left:10px;" %>
</div>
<div class="admin-skate-table">
  <table class="table">
    <thead class="admin-thead">
      <td>Skate Spot</td>
      <td>Submitted By</td>
      <td>State</td>
      <td>Approved</td>
      <td>Update</td>
      <td>Remove</td>
    </thead>
    <tbody>
      <tr><div class="approved">Approved Spots</div></tr>
        <% @approved_spots.each do |spot| %>
        <tr>
          <td><%= link_to spot.name, administrator_user_skate_spot_path(spot) %></td>
          <td><%= spot.city %></td>
          <td><%= spot.state %></td>
          <td><%= spot.approval %></td>
          <td><%= link_to "Deny", denial_administrator_user_skate_spot_path(spot), method: :post, class: "btn btn-warning btn-lrg" %></td>
          <td><%= link_to "Delete", administrator_user_skate_spot_path(spot), method: :delete, class: "btn btn-danger btn-lrg" %></td>
        </tr>
        <% end %>
    </tbody>
  </table>
</div>

<div class="admin-skate-table">
  <table class="table">
    <thead class="admin-thead">
      <td>Skate Spot</td>
      <td>Submitted By</td>
      <td>State</td>
      <td>Approved</td>
      <td>Update</td>
      <td>Remove</td>
    </thead>
    <tbody>
      <tr><div class="pending">Pending Spots</div></tr>
        <% @pending_spots.each do |spot| %>
          <tr>
            <td><%= link_to spot.name, administrator_skate_spot_path(spot) %></td>
            <td><%= spot.city %></td>
            <td><%= spot.state %></td>
            <td><%= spot.approval %></td>
            <td><%= link_to "Approve", approval_administrator_user_skate_spot_path(spot), method: :post, class: "btn btn-success btn-lrg"%></td>
            <td><%= link_to "Delete", administrator_skate_spot_path(spot), method: :delete, class: "btn btn-danger btn-lrg" %></td>
          </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/administrator/user_skate_spots/show.html.erb
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=762717537134813&version=v2.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

<br/>
<br/>
<br/>
<div class="container">
  <div>
    <%= link_to "Manage Skate Parks", administrator_skate_spots_path, class: "btn btn-primary btn-lrg", style: "margin-right:10px;" %>
  <%= link_to "Manage User Skate Spots", administrator_user_skate_spots_path, class: "btn btn-primary btn-lrg" %>
  <div class="spot-show" style="float:left">
    <h1><%= @user_spot.name %></h1>
    <p><%= image_tag(@user_spot.image, height: '300', width: '500', style: 'border-style:solid; border-width:3px; border-radius: 15px;') %></p>
    <p><%= link_to "Edit This Skatepark", edit_administrator_skate_spot_path(@user_spot), class: "btn btn-primary btn-lrg" %></p>
  </div>
  
      <div class="row skate-show">

        <div class="col-lg-6">
          <h4><%= @user_spot.address %></h4>
          <p><%= @user_spot.city%>, <%= @user_spot.state%> <%= @user_spot.zipcode%></p>
        </div>

        <div class="col-lg-6">
          <div id="map-show"></div>

        </div>
      
      </div>

    </div> <!-- /container -->


  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {
      zoom: 5
    }, 
    internal: {id: 'map-show'}}, 
    function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);

      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
  </script>