config/routes.rb
Rails.application.routes.draw do

root to: "static_pages#index"

  resources :skate_maps,        only: [:index, :show]
  resources :skate_spots,       only: [:index, :show]
  resources :user_skate_spots,  only: [:new, :index, :show, :create, :approve, :deny]

  get "/home",                   to: "static_pages#index"
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure",            to: redirect('/')
  get "/signout",                to: "sessions#destroy"


  namespace :administrator do
    resources :admins
    resources :users
    resources :skate_spots
    resources :user_skate_spots do
      member do
        post 'approval'
        post 'denial'
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :skate_spots,      only: [:index, :show]
      resources :user_skate_spots, only: [:index, :show]
    end
  end

end

app/models/user_skate_spot.rb
class UserSkateSpot < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :user

  scope :approved, -> { where(approval: true) }
  scope :pending,  -> { where(approval: false) }

  def approve(spot)
    spot.approval = true
    spot.save!
  end

  def deny(spot)
    spot.approval = false
    spot.save!
  end
end

app/controllers/administrator/user_skate_spots_controller.rb
class Administrator::UserSkateSpotsController < AdminsController

  def index
    @approved_spots = UserSkateSpot.approved
    @pending_spots  = UserSkateSpot.pending
  end

  def show
    @user_spot = UserSkateSpot.find(params[:id])
  end

  def destroy
    @spot = UserSkateSpot.find(params[:id])
    @spot.destroy
    redirect_to administrator_user_skate_spots_path
  end

  def approval
    UserSkateSpot.find(params[:id]).update_attribute(:approval, true)
    redirect_to :back
  end

  def denial
    UserSkateSpot.find(params[:id]).update_attribute(:approval, false)
    redirect_to :back
  end

  private

  def user_spot_params
    params.require(:user_skate_spot).permit(:approval)
  end
end

app/controllers/user_skate_spots_controller.rb
class UserSkateSpotsController < ApplicationController
  include UserSkateSpotsHelper

  def index
    @user_spots = UserSkateSpot.approved
    user_spots_to_hash(@user_spots)
  end

  def show
    @user_spot = UserSkateSpot.find(params[:id])
    user_spot_to_hash(@user_spot)
  end

  def new
    @spot = UserSkateSpot.new
  end

  def create
    @spot = UserSkateSpot.create(spot_params)
    flash[:notice] = "Your spot has been submitted, check your email for details on approval"
    redirect_to user_skate_spots_path
  end

  private

  def spot_params
    params.require(:user_skate_spot).permit(:name,
                                            :address,
                                            :city,
                                            :state,
                                            :zipcode,
                                            :latitude,
                                            :longitude,
                                            :image,
                                            :approval)
  end
end

app/helpers/user_skate_spots_helper.rb
module UserSkateSpotsHelper

  def user_spots_to_hash(user_spots)
    @hash   = Gmaps4rails.build_markers(user_spots) do |spot, marker|
      @spot = spot
      marker.infowindow render_to_string(:partial => "info")

      marker.lat spot.latitude
      marker.lng spot.longitude
    end
  end

  def user_spot_to_hash(user_spot)
    @hash  = Gmaps4rails.build_markers(user_spot) do |spot, marker|
      marker.lat spot.latitude
      marker.lng spot.longitude
    end
  end
end

app/views/user_skate_spots/_info.html.erb
<div class="info-window" style="color:black; float:center;">
  <p><b><%= link_to @spot.name, user_skate_spot_path(@spot) %></b></p>
  <p><%= @spot.address %><br/>
  <%= @spot.city %>,<%= @spot.state %> <%= @spot.zipcode %></p>
</div>

app/views/user_skate_spots/index.html.erb
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>


<div class="map-header">
  <p><h1>User Submitted Skate Spots</h1></p>
</div>

<div id="map-user"></div>

<div class="user-map-btn">
  <%= link_to "Submit a SeshON Spot", new_user_skate_spot_path, class: "btn btn-success btn-lrg", style: "border-style: solid; border-width: 2px; border-color: white;" %>
</div>

<br/>

<div class="container">
  <div class="row">
    <% @user_spots.each do |spot| %>
    <div class="col-lg-4">
      <div class="thumbnail">
        <div class="caption">
          <h4 class="caption-link"><%= link_to spot.name, user_skate_spot_path(spot) %></h4>
          <p><%= image_tag(spot.image, height: '100', width: '100', style: 'border-style:solid; border-width:2px; border-radius:5px; border-color:white;') %></p>
          <p style="color:white;"><%= spot.address %></p>
          <p style="color:white;"><%= spot.city %>, <%= spot.zipcode %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map-user'}}, function(){
      markers = handler.addMarkers(<%= raw @hash.to_json %>)

    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    });
  </script>

app/views/user_skate_spots/new.html.erb
<div class="form-container" style="padding-top:30px;">
  
  <div style="padding-top:1px;">
    
    <div class="form-header">
      <h3>Complete the form below to submit the details of a new skate spot location</h3>
      <h4>We will review your submission, and if it is approved we will add it to our list!</h4>
    </div>

    <div class="form-zipper">
      <%= form_for @spot, html: {multipart: true, class: "form-horizontal", role: "form", } do |f| %>
        <div class="form-group">
          <div class="col-md-6 col-md-offset-3">
            <%= f.label :name_your_spot, :class => 'control-label'%>
            <%= f.text_field :name, :class => 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-md-6 col-md-offset-3">
            <%= f.label 'Address / nearest cross streets', :class => 'control-label'%>      
            <%= f.text_field :address, :class => 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-md-5 col-md-offset-3">
            <%= f.label :city, :class => 'control-label'%>
            <%= f.text_field :city, :class => 'form-control' %>
          </div>
          <div class="col-md-1">
            <%= f.label :state, :class => 'control-label'%>
            <%= f.select(:state, options_for_select(us_states, "CO")) %>
          </div>
        </div>

        <div class="form-group" >
          <div class="col-md-3 col-md-offset-3">
            <%= f.label :zipcode, :class => 'control-label'%>
            <%= f.text_field :zipcode, :class => 'form-control' %>
          </div>
          <div>
            <p class="col-md-3"><%= f.label :image, class: "control-label"%></p>
            <div class="col-md-4"><%= f.file_field :image %></div>
          </div>
        </div>

        <div class="form-group" >
          <div class="col-md-3 col-md-offset-3">
            <%= f.label :latitude, :class => 'control-label'%>
            <%= f.text_field :latitude, :class => 'form-control', :id => "lat-field" %>
          </div>

          <div class="col-md-3">
            <%= f.label :longitude, :class => 'control-label'%>
            <%= f.text_field :longitude, :class => 'form-control', :id => "long-field" %>
          </div>
        </div>
        <div class="form-group" style="padding-bottom:15px;">
          <div class="col-md-4 col-md-offset-4">
              <%= f.submit "Submit", :class => "btn btn-success btn-lg", style:"border-style:solid; border-width:2px; border-color:white;" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){

    getLocation();
  })

  function getLocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(assignPosition);
    } else {
      x.innerHTML = "Geolocation is not supported by this browser.";
    }
  }

  function assignPosition(position) {
    var latitude  = position.coords.latitude;
    var longitude = position.coords.longitude;
    displayCoordinatesInFields(latitude, longitude);
  }

  function displayCoordinatesInFields(latitude, longitude) {
    $("#lat-field").val(latitude);
    $("#long-field").val(longitude);
  }
</script>

app/views/user_skate_spots/show.html.erb
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=762717537134813&version=v2.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

<br/>
<br/>
<br/>
<div class="container">
  <div class="spot-show" style="float:left">
    <h1><%= @user_spot.name %></h1>
    <p><%= image_tag(@user_spot.image, height: '300', width: '500', style: 'border-style:solid; border-width:3px; border-radius: 15px;') %></p>
  </div>
  
      <div class="row skate-show">

        <div class="col-lg-6">
          <h4><%= @user_spot.address %></h4>
          <p><%= @user_spot.city%>, <%= @user_spot.state%> <%= @user_spot.zipcode%></p>
          <% if current_user %>
            <div class="fb-share-button" data-href="<%= request.original_url %>" data-layout="button_count" data-width="200"></div>
          <% end %>
        </div>

        <div class="col-lg-6">
          <div id="user-map-show"></div>
        </div>
      
      </div>


    </div> <!-- /container -->


  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {
      zoom: 5
    }, 
    internal: {id: 'user-map-show'}}, 
    function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);

      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
  </script>