config/routes.rb
Rails.application.routes.draw do

root to: "static_pages#index"

  resources :skate_maps,        only: [:index, :show]
  resources :skate_spots,       only: [:index, :show]
  resources :user_skate_spots,  only: [:new, :index, :show, :create, :approve, :deny]

  get "/home",                   to: "static_pages#index"
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure",            to: redirect('/')
  get "/signout",                to: "sessions#destroy"


  namespace :administrator do
    resources :admins
    resources :users
    resources :skate_spots
    resources :user_skate_spots do
      member do
        post 'approval'
        post 'denial'
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :skate_spots,      only: [:index, :show]
      resources :user_skate_spots, only: [:index, :show]
    end
  end

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base

  belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_from_hash(hash)
    find_by_provider_and_uid(hash['provider'], hash['uid'])
  end

  def self.create_from_hash(hash, user = nil)
    user ||= User.create_from_hash!(hash)
    Authorization.create(user: user, uid: hash['uid'], provider: hash['provider'])
  end

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end

end

app/models/skate_spot.rb
class SkateSpot < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :skate_spots

  def self.from_omniauth(auth)
    user = find_with_auth(auth)
    create_with_auth(auth) unless user
    user
  end

  def self.find_with_auth(auth)
    User.find_by(
      provider: auth.provider,
      uid:      auth.uid
      )
  end

  def self.create_with_auth(auth)
    User.new do |user|
      user.name        = auth.info.name
      user.email       = auth.info.email
      user.oauth_token = auth.credentials.oauth_token
      user.provider    = auth.provider
      user.uid         = auth.uid
      user.save!
      # 1. Setup the User Mailer
      # 2. Setup Resque or Sidekiq 
        # Resque.enqueue(UserMailer.send_sign_up_notification(user).deliver)
        # -> loads into Redis
        # some_method.enqueue
      # --> UserMailer.send_sign_up_notification(user).deliver
    end
  end
end

app/models/user_skate_spot.rb
class UserSkateSpot < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :user

  scope :approved, -> { where(approval: true) }
  scope :pending,  -> { where(approval: false) }

  def approve(spot)
    spot.approval = true
    spot.save!
  end

  def deny(spot)
    spot.approval = false
    spot.save!
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authorize?

  private

  def authorize?
    redirect_to root_path unless current_user && current_user.role == "admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user ? true : false
  end

  def require_login
    unless logged_in?
      redirect_to root_path, notice: "Please log in."
    end
  end

  def admin?
    current_user.role == admin ? true : false
  end

  helper_method :current_user,
                :logged_in?,
                :require_login
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    user
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been signed out"
    redirect_to root_url
  end
end

app/controllers/skate_parks_controller.rb
class SkateParksController < ApplicationController

  def index
  end

end

app/controllers/skate_spots_controller.rb
class SkateSpotsController < ApplicationController
  include SkateSpotsHelper

  def index
    @spots = SkateSpot.all
    spots_to_hash(@spots)
  end

  def show
    @spot = SkateSpot.find(params[:id])
    spot_to_hash(@spot)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skate_maps_helper.rb
module SkateMapsHelper
end

app/helpers/skate_spots_helper.rb
module SkateSpotsHelper

  def spots_to_hash(spots)
    @hash   = Gmaps4rails.build_markers(spots) do |spot, marker|
      @spot = spot
      marker.infowindow render_to_string(:partial => "info")

      marker.lat spot.latitude
      marker.lng spot.longitude
    end
  end

  def spot_to_hash(spot)
    @hash  = Gmaps4rails.build_markers(spot) do |spot, marker|
      marker.lat spot.latitude
      marker.lng spot.longitude
    end
  end
end

app/helpers/states_helper.rb
module StatesHelper

  def us_states
    [
      ['AK', 'AK'],
	    ['AL', 'AL'],
	    ['AR', 'AR'],
	    ['AZ', 'AZ'],
	    ['CA', 'CA'],
	    ['CO', 'CO'],
	    ['CT', 'CT'],
	    ['DC', 'DC'],
	    ['DE', 'DE'],
	    ['FL', 'FL'],
	    ['GA', 'GA'],
	    ['HI', 'HI'],
	    ['IA', 'IA'],
	    ['ID', 'ID'],
	    ['IL', 'IL'],
	    ['IN', 'IN'],
	    ['KS', 'KS'],
	    ['KY', 'KY'],
	    ['LA', 'LA'],
	    ['MA', 'MA'],
	    ['MD', 'MD'],
	    ['ME', 'ME'],
	    ['MI', 'MI'],
	    ['MN', 'MN'],
	    ['MO', 'MO'],
	    ['MS', 'MS'],
	    ['MT', 'MT'],
	    ['NC', 'NC'],
	    ['ND', 'ND'],
	    ['NE', 'NE'],
	    ['NH', 'NH'],
	    ['NJ', 'NJ'],
	    ['NM', 'NM'],
	    ['NV', 'NV'],
	    ['NY', 'NY'],
	    ['OH', 'OH'],
	    ['OK', 'OK'],
	    ['OR', 'OR'],
	    ['PA', 'PA'],
	    ['RI', 'RI'],
	    ['SC', 'SC'],
	    ['SD', 'SD'],
	    ['TN', 'TN'],
	    ['TX', 'TX'],
	    ['UT', 'UT'],
	    ['VA', 'VA'],
	    ['VT', 'VT'],
	    ['WA', 'WA'],
	    ['WI', 'WI'],
	    ['WV', 'WV'],
	    ['WY', 'WY']
    ]
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_skate_spots_helper.rb
module UserSkateSpotsHelper

  def user_spots_to_hash(user_spots)
    @hash   = Gmaps4rails.build_markers(user_spots) do |spot, marker|
      @spot = spot
      marker.infowindow render_to_string(:partial => "info")

      marker.lat spot.latitude
      marker.lng spot.longitude
    end
  end

  def user_spot_to_hash(user_spot)
    @hash  = Gmaps4rails.build_markers(user_spot) do |spot, marker|
      marker.lat spot.latitude
      marker.lng spot.longitude
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-fixed-top z-index:10;" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <p><%= link_to "SeshON ninja", home_path, class: "masthead-brand navbar-brand font-effect-3d" %></p>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>&nbsp</li>
        <li>
          <%= link_to "Find Skate Parks", skate_spots_path %>
        </li>
        <li>
          <% if current_user %>
            <%= link_to "User SeshON Spots", user_skate_spots_path %>
          <% end %>
        </li>
      </ul>


      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if current_user && current_user.role =="admin" %>
            <%= link_to "Welcome '#{current_user.name}'", administrator_admins_path %>
          <% elsif current_user && current_user.role == "default" %>
            <%= link_to "Welcome '#{current_user.name}'" %>
          <% else %>
            <%= link_to "Sign In with Facebook", '/auth/facebook' %>
          <% end %>
        </li>
        <li>
          <% if current_user %>
            <%= link_to "Sign Out", signout_path %>
          <% end %>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">

  <title>SeshON</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Permanent+Marker&effect=3d' rel='stylesheet' type='text/css'>
</head>

<body>

  <div class="site-wrapper">

    <div class="site-wrapper-inner">

      <div class="cover-container">

        <div class="masthead clearfix">

          <div class="inner">
          <%= render partial: "layouts/navigation" %>
            
          </div>
    
      </div>
     
     <div class="alert-background text-center">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>">
          <%= message %>
        </div>
      <% end %>
      </div>

    </div>
    <%= yield %>
  </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="../../dist/js/bootstrap.min.js"></script>
  <script src="../../assets/js/docs.min.js"></script>
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>

</html>